############## NET - IOSTANDARD ##################
set_property CONFIG_VOLTAGE 1.8 [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 51.0 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]

#create_clock -name diff_clock_rtl_0_clk -period 10 [get_ports diff_clock_rtl_0_clk_p]
#create_clock -period 5.000 [get_ports DDR4_DIFF_CLK_clk_p]
create_clock -name sys_clk -period 10 [get_ports diff_clock_rtl_0_clk_p]

set_property PACKAGE_PIN AB7 [get_ports {diff_clock_rtl_0_clk_p[0]}]
set_property PACKAGE_PIN AF7 [get_ports {pcie_7x_mgt_rtl_0_txp[3]}]
set_property PACKAGE_PIN AE9 [get_ports {pcie_7x_mgt_rtl_0_txp[2]}]
set_property PACKAGE_PIN AD7 [get_ports {pcie_7x_mgt_rtl_0_txp[1]}]
set_property PACKAGE_PIN AC5 [get_ports {pcie_7x_mgt_rtl_0_txp[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports user_lnk_up_0]
set_property IOSTANDARD LVCMOS12 [get_ports reset_rtl_0]
set_property PACKAGE_PIN J9 [get_ports user_lnk_up_0]
set_property PACKAGE_PIN T19 [get_ports reset_rtl_0]

set_property IOSTANDARD LVCMOS33 [get_ports c0_init_calib_complete_0]
set_property PACKAGE_PIN H9 [get_ports c0_init_calib_complete_0]
set_property IOSTANDARD LVCMOS33 [get_ports ddr4_mig_resetn]
set_property PACKAGE_PIN K9 [get_ports ddr4_mig_resetn]

set_property PACKAGE_PIN T24 [get_ports DDR4_DIFF_CLK_clk_p]
set_property PACKAGE_PIN P24 [get_ports ddr4_rtl_0_act_n]
set_property PACKAGE_PIN P19 [get_ports ddr4_rtl_0_reset_n]
set_property PACKAGE_PIN R23 [get_ports {ddr4_rtl_0_odt[0]}]
set_property PACKAGE_PIN P25 [get_ports {ddr4_rtl_0_cs_n[0]}]
set_property PACKAGE_PIN P20 [get_ports {ddr4_rtl_0_cke[0]}]
set_property PACKAGE_PIN V24 [get_ports {ddr4_rtl_0_ck_t[0]}]
set_property PACKAGE_PIN R22 [get_ports {ddr4_rtl_0_bg[0]}]
set_property PACKAGE_PIN P21 [get_ports {ddr4_rtl_0_ba[0]}]
set_property PACKAGE_PIN P26 [get_ports {ddr4_rtl_0_ba[1]}]
set_property PACKAGE_PIN Y22 [get_ports {ddr4_rtl_0_adr[0]}]
set_property PACKAGE_PIN Y25 [get_ports {ddr4_rtl_0_adr[1]}]
set_property PACKAGE_PIN W23 [get_ports {ddr4_rtl_0_adr[2]}]
set_property PACKAGE_PIN V26 [get_ports {ddr4_rtl_0_adr[3]}]
set_property PACKAGE_PIN R26 [get_ports {ddr4_rtl_0_adr[4]}]
set_property PACKAGE_PIN U26 [get_ports {ddr4_rtl_0_adr[5]}]
set_property PACKAGE_PIN R21 [get_ports {ddr4_rtl_0_adr[6]}]
set_property PACKAGE_PIN W25 [get_ports {ddr4_rtl_0_adr[7]}]
set_property PACKAGE_PIN R20 [get_ports {ddr4_rtl_0_adr[8]}]
set_property PACKAGE_PIN Y26 [get_ports {ddr4_rtl_0_adr[9]}]
set_property PACKAGE_PIN R25 [get_ports {ddr4_rtl_0_adr[10]}]
set_property PACKAGE_PIN V23 [get_ports {ddr4_rtl_0_adr[11]}]
set_property PACKAGE_PIN AA24 [get_ports {ddr4_rtl_0_adr[12]}]
set_property PACKAGE_PIN W26 [get_ports {ddr4_rtl_0_adr[13]}]
#WE_B
set_property PACKAGE_PIN P23 [get_ports {ddr4_rtl_0_adr[14]}]
#CAS_B
set_property PACKAGE_PIN AA25 [get_ports {ddr4_rtl_0_adr[15]}]
#RAS_B
set_property PACKAGE_PIN T25 [get_ports {ddr4_rtl_0_adr[16]}]

set_property PACKAGE_PIN AE25 [get_ports {ddr4_rtl_0_dm_n[0]}]
set_property PACKAGE_PIN AE22 [get_ports {ddr4_rtl_0_dm_n[1]}]
set_property PACKAGE_PIN AD20 [get_ports {ddr4_rtl_0_dm_n[2]}]
set_property PACKAGE_PIN Y20 [get_ports {ddr4_rtl_0_dm_n[3]}]

set_property PACKAGE_PIN AC26 [get_ports {ddr4_rtl_0_dqs_t[0]}]
set_property PACKAGE_PIN AA22 [get_ports {ddr4_rtl_0_dqs_t[1]}]
set_property PACKAGE_PIN AC18 [get_ports {ddr4_rtl_0_dqs_t[2]}]
set_property PACKAGE_PIN AB17 [get_ports {ddr4_rtl_0_dqs_t[3]}]

set_property PACKAGE_PIN AB26 [get_ports {ddr4_rtl_0_dq[0]}]
set_property PACKAGE_PIN AB25 [get_ports {ddr4_rtl_0_dq[1]}]
set_property PACKAGE_PIN AF25 [get_ports {ddr4_rtl_0_dq[2]}]
set_property PACKAGE_PIN AF24 [get_ports {ddr4_rtl_0_dq[3]}]
set_property PACKAGE_PIN AD25 [get_ports {ddr4_rtl_0_dq[4]}]
set_property PACKAGE_PIN AD24 [get_ports {ddr4_rtl_0_dq[5]}]
set_property PACKAGE_PIN AC24 [get_ports {ddr4_rtl_0_dq[6]}]
set_property PACKAGE_PIN AB24 [get_ports {ddr4_rtl_0_dq[7]}]
set_property PACKAGE_PIN AE23 [get_ports {ddr4_rtl_0_dq[8]}]
set_property PACKAGE_PIN AD23 [get_ports {ddr4_rtl_0_dq[9]}]
set_property PACKAGE_PIN AC23 [get_ports {ddr4_rtl_0_dq[10]}]
set_property PACKAGE_PIN AC22 [get_ports {ddr4_rtl_0_dq[11]}]
set_property PACKAGE_PIN AE21 [get_ports {ddr4_rtl_0_dq[12]}]
set_property PACKAGE_PIN AD21 [get_ports {ddr4_rtl_0_dq[13]}]
set_property PACKAGE_PIN AC21 [get_ports {ddr4_rtl_0_dq[14]}]
set_property PACKAGE_PIN AB21 [get_ports {ddr4_rtl_0_dq[15]}]
set_property PACKAGE_PIN AD19 [get_ports {ddr4_rtl_0_dq[16]}]
set_property PACKAGE_PIN AC19 [get_ports {ddr4_rtl_0_dq[17]}]
set_property PACKAGE_PIN AF19 [get_ports {ddr4_rtl_0_dq[18]}]
set_property PACKAGE_PIN AF18 [get_ports {ddr4_rtl_0_dq[19]}]
set_property PACKAGE_PIN AF17 [get_ports {ddr4_rtl_0_dq[20]}]
set_property PACKAGE_PIN AE17 [get_ports {ddr4_rtl_0_dq[21]}]
set_property PACKAGE_PIN AE16 [get_ports {ddr4_rtl_0_dq[22]}]
set_property PACKAGE_PIN AD16 [get_ports {ddr4_rtl_0_dq[23]}]
set_property PACKAGE_PIN AB19 [get_ports {ddr4_rtl_0_dq[24]}]
set_property PACKAGE_PIN AA19 [get_ports {ddr4_rtl_0_dq[25]}]
set_property PACKAGE_PIN AB20 [get_ports {ddr4_rtl_0_dq[26]}]
set_property PACKAGE_PIN AA20 [get_ports {ddr4_rtl_0_dq[27]}]
set_property PACKAGE_PIN AA17 [get_ports {ddr4_rtl_0_dq[28]}]
set_property PACKAGE_PIN Y17 [get_ports {ddr4_rtl_0_dq[29]}]
set_property PACKAGE_PIN AA18 [get_ports {ddr4_rtl_0_dq[30]}]
set_property PACKAGE_PIN Y18 [get_ports {ddr4_rtl_0_dq[31]}]


