# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VIVADO231/ku5p/pcie_test/pcie_test.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_1/design_1_ddr4_0_1.xci
# IP: The module: 'design_1_ddr4_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_0/design_1_ddr4_0_1_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ddr4_0_1_microblaze_mcs || ORIG_REF_NAME==design_1_ddr4_0_1_microblaze_mcs} -quiet] -quiet

# Block Designs: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/bd_382b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b || ORIG_REF_NAME==bd_382b} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_0/bd_382b_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_microblaze_I_0 || ORIG_REF_NAME==bd_382b_microblaze_I_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_1/bd_382b_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_rst_0_0 || ORIG_REF_NAME==bd_382b_rst_0_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_2/bd_382b_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_ilmb_0 || ORIG_REF_NAME==bd_382b_ilmb_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_3/bd_382b_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_dlmb_0 || ORIG_REF_NAME==bd_382b_dlmb_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_4/bd_382b_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_dlmb_cntlr_0 || ORIG_REF_NAME==bd_382b_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_5/bd_382b_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_ilmb_cntlr_0 || ORIG_REF_NAME==bd_382b_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_6/bd_382b_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_lmb_bram_I_0 || ORIG_REF_NAME==bd_382b_lmb_bram_I_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_7/bd_382b_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_382b_second_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_8/bd_382b_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_382b_second_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_9/bd_382b_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_382b_second_lmb_bram_I_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_10/bd_382b_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_iomodule_0_0 || ORIG_REF_NAME==bd_382b_iomodule_0_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_1/design_1_ddr4_0_1_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ddr4_0_1_phy || ORIG_REF_NAME==design_1_ddr4_0_1_phy} -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_0/bd_382b_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_microblaze_I_0 || ORIG_REF_NAME==bd_382b_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_0/bd_382b_microblaze_I_0_ooc_debug.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_1/bd_382b_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_rst_0_0 || ORIG_REF_NAME==bd_382b_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_1/bd_382b_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_rst_0_0 || ORIG_REF_NAME==bd_382b_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_2/bd_382b_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_ilmb_0 || ORIG_REF_NAME==bd_382b_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_3/bd_382b_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_dlmb_0 || ORIG_REF_NAME==bd_382b_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_6/bd_382b_lmb_bram_I_0_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_9/bd_382b_second_lmb_bram_I_0_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_10/bd_382b_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_iomodule_0_0 || ORIG_REF_NAME==bd_382b_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/bd_382b_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_0/design_1_ddr4_0_1_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ddr4_0_1_microblaze_mcs || ORIG_REF_NAME==design_1_ddr4_0_1_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_0/design_1_ddr4_0_1_microblaze_mcs_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_1/par/design_1_ddr4_0_1_phy_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/design_1_ddr4_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ddr4_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/par/design_1_ddr4_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ddr4_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/VIVADO231/ku5p/pcie_test/pcie_test.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_1/design_1_ddr4_0_1.xci
# IP: The module: 'design_1_ddr4_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_0/design_1_ddr4_0_1_microblaze_mcs.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ddr4_0_1_microblaze_mcs || ORIG_REF_NAME==design_1_ddr4_0_1_microblaze_mcs} -quiet] -quiet

# Block Designs: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/bd_382b.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b || ORIG_REF_NAME==bd_382b} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_0/bd_382b_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_microblaze_I_0 || ORIG_REF_NAME==bd_382b_microblaze_I_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_1/bd_382b_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_rst_0_0 || ORIG_REF_NAME==bd_382b_rst_0_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_2/bd_382b_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_ilmb_0 || ORIG_REF_NAME==bd_382b_ilmb_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_3/bd_382b_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_dlmb_0 || ORIG_REF_NAME==bd_382b_dlmb_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_4/bd_382b_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_dlmb_cntlr_0 || ORIG_REF_NAME==bd_382b_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_5/bd_382b_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_ilmb_cntlr_0 || ORIG_REF_NAME==bd_382b_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_6/bd_382b_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_lmb_bram_I_0 || ORIG_REF_NAME==bd_382b_lmb_bram_I_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_7/bd_382b_second_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_382b_second_dlmb_cntlr_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_8/bd_382b_second_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_382b_second_ilmb_cntlr_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_9/bd_382b_second_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_382b_second_lmb_bram_I_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_10/bd_382b_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_382b_iomodule_0_0 || ORIG_REF_NAME==bd_382b_iomodule_0_0} -quiet] -quiet

# IP: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_1/design_1_ddr4_0_1_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ddr4_0_1_phy || ORIG_REF_NAME==design_1_ddr4_0_1_phy} -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_0/bd_382b_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_microblaze_I_0 || ORIG_REF_NAME==bd_382b_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_0/bd_382b_microblaze_I_0_ooc_debug.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_1/bd_382b_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_rst_0_0 || ORIG_REF_NAME==bd_382b_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_1/bd_382b_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_rst_0_0 || ORIG_REF_NAME==bd_382b_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_2/bd_382b_ilmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_ilmb_0 || ORIG_REF_NAME==bd_382b_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_3/bd_382b_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_dlmb_0 || ORIG_REF_NAME==bd_382b_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_6/bd_382b_lmb_bram_I_0_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_9/bd_382b_second_lmb_bram_I_0_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/ip/ip_10/bd_382b_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_382b_iomodule_0_0 || ORIG_REF_NAME==bd_382b_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/bd_0/bd_382b_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_0/design_1_ddr4_0_1_microblaze_mcs_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ddr4_0_1_microblaze_mcs || ORIG_REF_NAME==design_1_ddr4_0_1_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_0/design_1_ddr4_0_1_microblaze_mcs_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/ip_1/par/design_1_ddr4_0_1_phy_ooc.xdc

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/design_1_ddr4_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ddr4_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/VIVADO231/ku5p/pcie_test/pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_1/par/design_1_ddr4_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ddr4_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
